### ISSUE TITLE
发送图片和表情闪退

### ISSUE THREAD

**Issue by zdby** [hillfly/WifiChat#13]
04-10 21:15:07.561: W/System.err(28173): java.lang.NullPointerException
04-10 21:15:07.569: W/System.err(28173):    at hillfly.wifichat.adapter.FriendsAdapter.getView(FriendsAdapter.java:54)
04-10 21:15:07.569: W/System.err(28173):    at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
04-10 21:15:07.570: W/System.err(28173):    at android.widget.AbsListView.obtainView(AbsListView.java:2380)
04-10 21:15:07.570: W/System.err(28173):    at android.widget.ListView.makeAndAddView(ListView.java:1816)
04-10 21:15:07.570: W/System.err(28173):    at android.widget.ListView.fillDown(ListView.java:702)
04-10 21:15:07.571: W/System.err(28173):    at android.widget.ListView.fillFromTop(ListView.java:763)
04-10 21:15:07.572: W/System.err(28173):    at android.widget.ListView.layoutChildren(ListView.java:1635)
04-10 21:15:07.573: W/System.err(28173):    at android.widget.AbsListView.onLayout(AbsListView.java:2187)
04-10 21:15:07.573: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.575: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.577: W/System.err(28173):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1914)
04-10 21:15:07.578: W/System.err(28173):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1768)
04-10 21:15:07.578: W/System.err(28173):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1677)
04-10 21:15:07.579: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.580: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.581: W/System.err(28173):    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
04-10 21:15:07.581: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.583: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.583: W/System.err(28173):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
04-10 21:15:07.585: W/System.err(28173):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
04-10 21:15:07.585: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.586: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.592: W/System.err(28173):    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
04-10 21:15:07.592: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.596: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.597: W/System.err(28173):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
04-10 21:15:07.597: W/System.err(28173):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
04-10 21:15:07.597: W/System.err(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.597: W/System.err(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.597: W/System.err(28173):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2361)
04-10 21:15:07.597: W/System.err(28173):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2064)
04-10 21:15:07.597: W/System.err(28173):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1210)
04-10 21:15:07.597: W/System.err(28173):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
04-10 21:15:07.598: W/System.err(28173):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
04-10 21:15:07.598: W/System.err(28173):    at android.view.Choreographer.doCallbacks(Choreographer.java:610)
04-10 21:15:07.598: W/System.err(28173):    at android.view.Choreographer.doFrame(Choreographer.java:578)
04-10 21:15:07.599: W/System.err(28173):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:793)
04-10 21:15:07.599: W/System.err(28173):    at android.os.Handler.handleCallback(Handler.java:808)
04-10 21:15:07.599: W/System.err(28173):    at android.os.Handler.dispatchMessage(Handler.java:103)
04-10 21:15:07.599: W/System.err(28173):    at android.os.Looper.loop(Looper.java:193)
04-10 21:15:07.599: W/System.err(28173):    at android.app.ActivityThread.main(ActivityThread.java:5551)
04-10 21:15:07.599: W/System.err(28173):    at java.lang.reflect.Method.invokeNative(Native Method)
04-10 21:15:07.599: W/System.err(28173):    at java.lang.reflect.Method.invoke(Method.java:515)
04-10 21:15:07.599: W/System.err(28173):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
04-10 21:15:07.599: W/System.err(28173):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
04-10 21:15:07.599: W/System.err(28173):    at dalvik.system.NativeStart.main(Native Method)
04-10 21:15:07.600: W/dalvikvm(28173): threadid=1: calling UncaughtExceptionHandler
04-10 21:15:07.603: E/AndroidRuntime(28173): FATAL EXCEPTION: main
04-10 21:15:07.603: E/AndroidRuntime(28173): Process: hillfly.wifichat, PID: 28173
04-10 21:15:07.603: E/AndroidRuntime(28173): java.lang.NullPointerException
04-10 21:15:07.603: E/AndroidRuntime(28173):    at hillfly.wifichat.adapter.FriendsAdapter.getView(FriendsAdapter.java:54)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.AbsListView.obtainView(AbsListView.java:2380)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.ListView.makeAndAddView(ListView.java:1816)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.ListView.fillDown(ListView.java:702)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.ListView.fillFromTop(ListView.java:763)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.ListView.layoutChildren(ListView.java:1635)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.AbsListView.onLayout(AbsListView.java:2187)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1914)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1768)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.LinearLayout.onLayout(LinearLayout.java:1677)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1589)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:374)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.View.layout(View.java:15169)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewGroup.layout(ViewGroup.java:4882)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2361)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2064)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1210)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6408)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:807)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.Choreographer.doCallbacks(Choreographer.java:610)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.Choreographer.doFrame(Choreographer.java:578)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:793)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.os.Handler.handleCallback(Handler.java:808)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.os.Handler.dispatchMessage(Handler.java:103)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.os.Looper.loop(Looper.java:193)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at android.app.ActivityThread.main(ActivityThread.java:5551)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at java.lang.reflect.Method.invokeNative(Native Method)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at java.lang.reflect.Method.invoke(Method.java:515)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:730)
04-10 21:15:07.603: E/AndroidRuntime(28173):    at dalvik.system.NativeStart.main(Native Method)

**Comment by zdby** [comment]
normal mode

**Comment by zdby** [comment]
04-10 21:23:14.458: W/System.err(30477): java.net.SocketException: sendto failed: ENETUNREACH (Network is unreachable)
04-10 21:23:14.461: W/System.err(30477):    at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:543)
04-10 21:23:14.463: W/System.err(30477):    at libcore.io.IoBridge.sendto(IoBridge.java:512)
04-10 21:23:14.465: W/System.err(30477):    at java.net.PlainDatagramSocketImpl.send(PlainDatagramSocketImpl.java:198)
04-10 21:23:14.468: W/System.err(30477):    at java.net.DatagramSocket.send(DatagramSocket.java:281)
04-10 21:23:14.470: W/System.err(30477):    at hillfly.wifichat.common.socket.udp.UDPMessageListener$1.run(UDPMessageListener.java:432)
04-10 21:23:14.472: W/System.err(30477):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-10 21:23:14.475: W/System.err(30477):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-10 21:23:14.478: W/System.err(30477):    at java.lang.Thread.run(Thread.java:841)
04-10 21:23:14.480: W/System.err(30477): Caused by: libcore.io.ErrnoException: sendto failed: ENETUNREACH (Network is unreachable)
04-10 21:23:14.484: W/System.err(30477):    at libcore.io.Posix.sendtoBytes(Native Method)
04-10 21:23:14.486: W/System.err(30477):    at libcore.io.Posix.sendto(Posix.java:156)
04-10 21:23:14.488: W/System.err(30477):    at libcore.io.BlockGuardOs.sendto(BlockGuardOs.java:177)
04-10 21:23:14.490: W/System.err(30477):    at libcore.io.IoBridge.sendto(IoBridge.java:510)
04-10 21:23:14.492: W/System.err(30477):    ... 6 more
04-10 21:23:14.495: E/WiFiChat(30477): [ pool-1-thread-1: UDPMessageListener.java:437 run ] - 发送UDP数据包失败

**Comment by hillfly** [comment]
是自创热点还是加入的wifi？我拿了几台机子测试了下都OK呀。
麻烦提供下机子型号和Android版本

**Comment by zdby** [comment]
一台机器自创热点（华为荣耀3c    4.4.2），另一台机器加入这个热点（聆韵   4.2.2），你测试的机子是哪个版本的呢？

**Comment by zdby** [comment]
我后来试了试，上面的两个机子反过来（聆韵自创热点，华为加入热点）能正常发送表情和图片，有点奇怪。我还问个问题，没有看到发送文件的按钮，那个加号只能发送图片或者拍照呢

**Comment by hillfly** [comment]
官方论坛很多开发者反馈荣耀3C创建热点有问题，跟其它机子机制不太一样，我手头木有自己可以调。关于发送文件模块，暂时屏蔽了，有问题，改了再开。
